modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Direwolf20-MC/MiningGadgets"
license="MIT (https://github.com/Direwolf20-MC/MiningGadgets/blob/master/LICENSE.txt)"

[[mods]]
modId="mininggadgets"
version="${file.jarVersion}"
displayName="Mining Gadgets"
updateJSONURL="https://raw.githubusercontent.com/Direwolf20-MC/MiningGadgets/master/update.json"
displayURL="https://github.com/Direwolf20-MC/MiningGadgets/"
logoFile="mininggadgets-logo.png"
credits="CPW and Lex for making Forge the best API ever!!"
authors="Direwolf20"
description='''Mining is better with lasers.'''

#forge
[[dependencies.mininggadgets]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

#minecraft
[[dependencies.mininggadgets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
